# Generated by Django 5.1.3 on 2024-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dhmos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Πελάτης')),
                ('address', models.CharField(blank=True, default='-', max_length=100, verbose_name='Διεύθυνση')),
                ('city', models.CharField(blank=True, default='-', max_length=100, verbose_name='Πόλη')),
                ('phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax')),
                ('teamviewer', models.CharField(blank=True, max_length=60, verbose_name='TeamViewer')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, verbose_name='Πληροφορίες')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Κατάσταση')),
            ],
            options={
                'verbose_name': 'ACS Φορέας',
                'verbose_name_plural': 'ACS Φορέας',
                'ordering': ['name'],
            },
        ),
    ]
