# Generated by Django 5.1.3 on 2024-11-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, null=True, verbose_name='Όνομα')),
                ('lastname', models.CharField(max_length=150, null=True, verbose_name='Επώνυμο')),
                ('tmhma', models.CharField(blank=True, choices=[('1', 'Οικονομική'), ('2', 'Τεχνική'), ('3', 'Διοικητική'), ('4', 'Γραφείο Προσωπικού'), ('5', 'Μισθοδοσία'), ('6', 'Γραφείο Δημάρχου'), ('7', 'Τμήμα Πληροφορικής'), ('8', 'Ληξιαρχείο'), ('9', 'Αντιδήμαρχος'), ('10', 'Γραφείο Κίνησης'), ('11', 'Δήμαρχος'), ('12', 'Γενικός Γραμματέας'), ('13', 'Υπηρεσία Καθαριότητας'), ('14', 'Γραφείο Πρωτοκόλλου'), ('15', 'Ειδικός Συνεργάτης')], default='-', max_length=100, null=True, verbose_name='Υπηρεσία')),
                ('phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('cellphone', models.CharField(blank=True, max_length=30, verbose_name='Κινητό')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, verbose_name='Πληροφορίες')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Κατάσταση')),
                ('dhmos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foreas.dhmos', verbose_name='Πελάτης')),
            ],
            options={
                'verbose_name': 'ACS Στοιχεία Επικοινωνίας Υπαλλήλων',
                'verbose_name_plural': 'ACS Στοιχεία Επικοινωνίας Υπαλλήλων',
            },
        ),
    ]
