# Generated by Django 5.1.3 on 2024-12-03 10:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'ACS Φορέας', 'verbose_name_plural': 'ACS Φορέας'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_title',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_title_alias',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone_number_1',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone_number_2',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='organization',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='organization',
            name='info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Πληροφορίες'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Κατάσταση'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='ACS', max_length=100, verbose_name='Πελάτης'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Τηλέφωνο'),
        ),
        migrations.AddField(
            model_name='organization',
            name='teamviewer',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='TeamViewer'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, null=True, verbose_name='Όνομα')),
                ('lastname', models.CharField(max_length=150, null=True, verbose_name='Επώνυμο')),
                ('tmhma', models.CharField(blank=True, choices=[('1', 'Οικονομική'), ('2', 'Τεχνική'), ('3', 'Διοικητική'), ('4', 'Γραφείο Προσωπικού'), ('5', 'Μισθοδοσία'), ('6', 'Γραφείο Δημάρχου'), ('7', 'Τμήμα Πληροφορικής'), ('8', 'Ληξιαρχείο'), ('9', 'Αντιδήμαρχος'), ('10', 'Γραφείο Κίνησης'), ('11', 'Δήμαρχος'), ('12', 'Γενικός Γραμματέας'), ('13', 'Υπηρεσία Καθαριότητας'), ('14', 'Γραφείο Πρωτοκόλλου'), ('15', 'Ειδικός Συνεργάτης')], max_length=100, null=True, verbose_name='Υπηρεσία')),
                ('phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('cellphone', models.CharField(blank=True, max_length=30, verbose_name='Κινητό')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, verbose_name='Πληροφορίες')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Κατάσταση')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Πελάτης')),
            ],
            options={
                'verbose_name': 'ACS Στοιχεία Επικοινωνίας Υπαλλήλων',
                'verbose_name_plural': 'ACS Στοιχεία Επικοινωνίας Υπαλλήλων',
            },
        ),
        migrations.CreateModel(
            name='Ergasies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importdate', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Ημ. Κατ.')),
                ('app', models.CharField(blank=True, choices=[('ΤΑΠ', 'ΤΑΠ'), ('Μισθοδοσία', 'Μισθοδοσία'), ('Διαχείριση Προσωπικού', 'Διαχείριση Προσωπικού'), ('Διαχείριση Μισθωμάτων', 'Διαχείριση Μισθωμάτων'), ('Λογιστική', 'Λογιστική'), ('Μητρώο Πολιτών', 'Μητρώο Πολιτών'), ('Ύδρευση', 'Ύδρευση'), ('Αποφάσεις', 'Αποφάσεις'), ('Πρωτόκολλο', 'Πρωτόκολλο'), ('Γραφείο Κίνησης', 'Γραφείο Κίνησης'), ('Διαύγεια', 'Διαύγεια'), ('Έσοδα', 'Έσοδα'), ('Κοιμητήρια', 'Κοιμητήρια'), ('ΚΟΚ', 'ΚΟΚ'), ('Δημοτικός φόρος', 'Δημοτικός φόρος'), ('Site', 'Site'), ('Web Άδειες', 'Web Άδειες'), ('Πρακτικό', 'Πρακτικό'), ('Hardware', 'Hardware'), ('Ύδατα', 'Ύδατα'), ('OPEN1|Process', 'OPEN1|Process'), ('OPEN1|Fin', 'OPEN1|Fin'), ('OPEN1|HR', 'OPEN1|HR'), ('OPEN1|Property', 'OPEN1|Property'), ('Open1|Decisions', 'Open1|Decisions'), ('Open1|Entrance', 'Open1|Entrance'), ('OPEN1|Fleet', 'OPEN1|Fleet'), ('OPEN1|Project360', 'OPEN1|Project360'), ('4myCity', '4myCity'), ('Easy Pay', 'EasyPay'), ('Εσωτερικός Έλεγχος-Επιχ. Συν.', 'Εσωτερικός Έλεγχος-Επιχ. Συν.'), ('Ηλεκτ.Εισπρ. ΔΙΑΣ', 'Ηλεκτ.Εισπρ. ΔΙΑΣ'), ('Διαχείριση Ποιότητας - ISO', 'Διαχείριση Ποιότητας - ISO')], max_length=100, verbose_name='Εφαρμογή')),
                ('jobtype', models.CharField(choices=[('TeamViewer', 'TeamViewer'), ('Επίσκεψη', 'Επίσκεψη'), ('Γραφείο', 'Γραφείο'), ('Webinar-Zoom', 'Webinar-Zoom')], default='TeamViewer', max_length=100, verbose_name='Τύπος Εργασίας')),
                ('info', models.TextField(max_length=1000, verbose_name='Περιγραφή')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Σημειώσεις')),
                ('time', models.FloatField(verbose_name='Διάρκεια')),
                ('name', models.CharField(blank=True, help_text='Επώνυμο-Όνομα', max_length=100, null=True, verbose_name='Υπάλληλος Επικοιν.')),
                ('ticketid', models.CharField(blank=True, max_length=50, verbose_name='Αίτημα OTS')),
                ('employee', models.PositiveIntegerField(verbose_name='Υπάλληλος')),
                ('employee1', models.ForeignKey(default='-', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('organization', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Πελάτης')),
            ],
            options={
                'verbose_name': 'ACS Εργασίες Φορέα',
                'verbose_name_plural': 'ACS Εργασίες Φορέα',
                'ordering': ['importdate'],
                'indexes': [models.Index(fields=['importdate', 'employee'], name='organizatio_importd_6284af_idx')],
            },
        ),
    ]
