# Generated by Django 5.1.3 on 2024-12-03 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ergasies',
            new_name='organizatio_importd_b2e4cb_idx',
            old_name='organizatio_importd_6284af_idx',
        ),
        migrations.RemoveField(
            model_name='ergasies',
            name='employee1',
        ),
        migrations.AlterField(
            model_name='ergasies',
            name='employee',
            field=models.ForeignKey(default='-', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος'),
        ),
    ]
