# Generated by Django 5.1.3 on 2024-12-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_rename_organizatio_importd_6284af_idx_organizatio_importd_b2e4cb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergasies',
            name='jobtype',
            field=models.CharField(choices=[('1', 'TeamViewer'), ('2', 'Επίσκεψη'), ('3', 'Γραφείο'), ('4', 'Webinar-Zoom')], default='TeamViewer', max_length=100, verbose_name='Τύπος Εργασίας'),
        ),
    ]
