# Generated by Django 5.1.3 on 2024-12-04 10:23

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_ergasies_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'ACS Εργασίες Φορέα',
                'verbose_name_plural': 'ACS Εργασίες Φορέα',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='organizatio_title_e9b0a0_idx')],
            },
        ),
    ]
