# Generated by Django 5.1.3 on 2024-12-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['title'], 'verbose_name': 'OTS Εφαρμογές', 'verbose_name_plural': 'OTS Εφαρμογές'},
        ),
        migrations.RemoveField(
            model_name='ergasies',
            name='name',
        ),
        migrations.AddField(
            model_name='ergasies',
            name='org_employee',
            field=models.ForeignKey(default='408', on_delete=django.db.models.deletion.PROTECT, to='organization.employee', verbose_name='Πελάτης'),
        ),
    ]
