# Generated by Django 5.1.3 on 2024-12-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_application_options_remove_ergasies_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergasies',
            name='org_employee',
            field=models.ForeignKey(default='408', on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='Πελάτης'),
        ),
    ]
