# Generated by Django 5.1.3 on 2024-12-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_application_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='organization',
            new_name='dhmos',
        ),
    ]
