# Generated by Django 5.1.3 on 2024-12-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_rename_organization_employee_dhmos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dhmos',
            new_name='organization',
        ),
    ]
