# Generated by Django 5.1.3 on 2024-12-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_rename_dhmos_employee_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dhmos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
