# Generated by Django 5.1.3 on 2024-12-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_employee_dhmos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dhmos',
        ),
    ]
