# Generated by Django 5.1.3 on 2024-12-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_remove_employee_dhmos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Dhmos',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='organization',
            new_name='dhmos',
        ),
        migrations.RenameField(
            model_name='ergasies',
            old_name='organization',
            new_name='dhmos',
        ),
    ]
