# Generated by Django 5.1.4 on 2024-12-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_employee_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='old_id',
            field=models.IntegerField(null=True, verbose_name='old_id'),
        ),
    ]
