# Generated by Django 5.1.4 on 2024-12-10 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_application_old_id_ergasies_old_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergasies',
            name='employee',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος'),
        ),
        migrations.AlterField(
            model_name='ergasies',
            name='org_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='Πελάτης'),
        ),
        migrations.AlterField(
            model_name='ergasies',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Πελάτης'),
        ),
    ]
