# Generated by Django 5.1.4 on 2024-12-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_alter_ergasies_employee_alter_ergasies_org_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergasies',
            name='time',
            field=models.FloatField(blank=True, null=True, verbose_name='Διάρκεια'),
        ),
    ]
