# Generated by Django 5.1.4 on 2024-12-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_alter_ergasies_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergasies',
            name='org_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='Πελάτης'),
        ),
    ]
