# Generated by Django 5.1.4 on 2024-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_alter_ergasies_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Πόλη'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fax',
            field=models.CharField(max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='info',
            field=models.TextField(max_length=1000, verbose_name='Πληροφορίες'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Πελάτης'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='old_id',
            field=models.IntegerField(verbose_name='old_id'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Τηλέφωνο'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='teamviewer',
            field=models.CharField(max_length=60, verbose_name='TeamViewer'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(max_length=250),
        ),
    ]
