# Generated by Django 5.1.4 on 2024-12-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_alter_organization_address_alter_organization_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='old_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='old_id'),
        ),
    ]
