# Generated by Django 5.1.4 on 2024-12-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0025_alter_organization_old_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="old_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="old_id"),
        ),
    ]
