# Generated by Django 5.1.4 on 2024-12-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0026_alter_application_old_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="old_id",
        ),
    ]
