# Generated by Django 5.1.4 on 2024-12-30 17:40

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0028_organization_created_organization_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Κατάσταση"),
                ),
            ],
            options={
                "verbose_name": "Υπηρεσίες Οργανισμών",
                "verbose_name_plural": "Υπηρεσίες Οργανισμών",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="organizatio_name_93bf26_idx")
                ],
            },
        ),
    ]
