# Generated by Django 5.2 on 2026-10-08 08:14

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος έργου')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Περιγραφή')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία έναρξης')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία λήξης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('info', models.TextField(blank=True, max_length=2000, verbose_name='Πληροφορίες')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Οργανισμός')),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Υπεύθυνος')),
            ],
            options={
                'verbose_name': 'historical Έργο',
                'verbose_name_plural': 'historical Έργα',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος έργου')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Περιγραφή')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία έναρξης')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία λήξης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('info', models.TextField(blank=True, max_length=2000, verbose_name='Πληροφορίες')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organizations.organization', verbose_name='Οργανισμός')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='Υπεύθυνος')),
            ],
            options={
                'verbose_name': 'Έργο',
                'verbose_name_plural': 'Έργα',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalProjectDocument',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='Έντυπο')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Περιγραφή')),
                ('due_date', models.DateField(db_index=True, verbose_name='Ημερομηνία παράδοσης')),
                ('file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Αρχείο')),
                ('submitted', models.BooleanField(default=False, verbose_name='Υποβλήθηκε')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία υποβολής')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='Σημειώσεις')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Υπεύθυνος')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'historical Έντυπο έργου',
                'verbose_name_plural': 'historical Έντυπα έργου',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Έντυπο')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Περιγραφή')),
                ('due_date', models.DateField(db_index=True, verbose_name='Ημερομηνία παράδοσης')),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/documents/', verbose_name='Αρχείο')),
                ('submitted', models.BooleanField(default=False, verbose_name='Υποβλήθηκε')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία υποβολής')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='Σημειώσεις')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Έργο')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_project_documents', to=settings.AUTH_USER_MODEL, verbose_name='Υπεύθυνος')),
            ],
            options={
                'verbose_name': 'Έντυπο έργου',
                'verbose_name_plural': 'Έντυπα έργου',
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalProjectReminder',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('days_before', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ημέρες πριν')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία αποστολής')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projectdocument', verbose_name='Έντυπο')),
            ],
            options={
                'verbose_name': 'historical Υπενθύμιση εντύπου',
                'verbose_name_plural': 'historical Υπενθυμίσεις εντύπων',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectReminder',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_before', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ημέρες πριν')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία αποστολής')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='projects.projectdocument', verbose_name='Έντυπο')),
            ],
            options={
                'verbose_name': 'Υπενθύμιση εντύπου',
                'verbose_name_plural': 'Υπενθυμίσεις εντύπων',
                'ordering': ('days_before',),
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'is_active'], name='projects_pr_organiz_9116bf_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['end_date'], name='projects_pr_end_dat_f8a25b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['responsible', 'is_active'], name='projects_pr_respons_5cba5c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'due_date'], name='projects_pr_project_3cf3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['submitted', 'due_date'], name='projects_pr_submitt_95436a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['responsible', 'submitted', 'due_date'], name='projects_pr_respons_3aa73d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreminder',
            index=models.Index(fields=['is_active', 'sent_at'], name='projects_pr_is_acti_dc6cf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectreminder',
            constraint=models.UniqueConstraint(fields=('document', 'days_before'), name='unique_document_reminder_days'),
        ),
    ]
