# Generated by Django 5.2 on 2026-10-09 05:53

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.projects.models.project_document_upload_path, verbose_name='Αρχείο'),
        ),
    ]
