# Generated by Django 5.2 on 2026-10-09 05:55

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectdocument',
            name='file',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.projects.models.project_document_upload_path, verbose_name='Αρχείο'),
        ),
    ]
