# Generated by Django 5.1.3 on 2024-11-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreas', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhmos',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='dhmos',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Πόλη'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tmhma',
            field=models.CharField(blank=True, choices=[('1', 'Οικονομική'), ('2', 'Τεχνική'), ('3', 'Διοικητική'), ('4', 'Γραφείο Προσωπικού'), ('5', 'Μισθοδοσία'), ('6', 'Γραφείο Δημάρχου'), ('7', 'Τμήμα Πληροφορικής'), ('8', 'Ληξιαρχείο'), ('9', 'Αντιδήμαρχος'), ('10', 'Γραφείο Κίνησης'), ('11', 'Δήμαρχος'), ('12', 'Γενικός Γραμματέας'), ('13', 'Υπηρεσία Καθαριότητας'), ('14', 'Γραφείο Πρωτοκόλλου'), ('15', 'Ειδικός Συνεργάτης')], max_length=100, null=True, verbose_name='Υπηρεσία'),
        ),
    ]
