# Generated by Django 5.1.3 on 2024-12-03 06:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreas', '0003_alter_dhmos_address_alter_dhmos_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ergasies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importdate', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Ημ. Κατ.')),
                ('app', models.CharField(blank=True, choices=[('ΤΑΠ', 'ΤΑΠ'), ('Μισθοδοσία', 'Μισθοδοσία'), ('Διαχείριση Προσωπικού', 'Διαχείριση Προσωπικού'), ('Διαχείριση Μισθωμάτων', 'Διαχείριση Μισθωμάτων'), ('Λογιστική', 'Λογιστική'), ('Μητρώο Πολιτών', 'Μητρώο Πολιτών'), ('Ύδρευση', 'Ύδρευση'), ('Αποφάσεις', 'Αποφάσεις'), ('Πρωτόκολλο', 'Πρωτόκολλο'), ('Γραφείο Κίνησης', 'Γραφείο Κίνησης'), ('Διαύγεια', 'Διαύγεια'), ('Έσοδα', 'Έσοδα'), ('Κοιμητήρια', 'Κοιμητήρια'), ('ΚΟΚ', 'ΚΟΚ'), ('Δημοτικός φόρος', 'Δημοτικός φόρος'), ('Site', 'Site'), ('Web Άδειες', 'Web Άδειες'), ('Πρακτικό', 'Πρακτικό'), ('Hardware', 'Hardware'), ('Ύδατα', 'Ύδατα'), ('OPEN1|Process', 'OPEN1|Process'), ('OPEN1|Fin', 'OPEN1|Fin'), ('OPEN1|HR', 'OPEN1|HR'), ('OPEN1|Property', 'OPEN1|Property'), ('Open1|Decisions', 'Open1|Decisions'), ('Open1|Entrance', 'Open1|Entrance'), ('OPEN1|Fleet', 'OPEN1|Fleet'), ('OPEN1|Project360', 'OPEN1|Project360'), ('4myCity', '4myCity'), ('Easy Pay', 'EasyPay'), ('Εσωτερικός Έλεγχος-Επιχ. Συν.', 'Εσωτερικός Έλεγχος-Επιχ. Συν.'), ('Ηλεκτ.Εισπρ. ΔΙΑΣ', 'Ηλεκτ.Εισπρ. ΔΙΑΣ'), ('Διαχείριση Ποιότητας - ISO', 'Διαχείριση Ποιότητας - ISO')], max_length=100, verbose_name='Εφαρμογή')),
                ('jobtype', models.CharField(choices=[('TeamViewer', 'TeamViewer'), ('Επίσκεψη', 'Επίσκεψη'), ('Γραφείο', 'Γραφείο'), ('Webinar-Zoom', 'Webinar-Zoom')], default='TeamViewer', max_length=100, verbose_name='Τύπος Εργασίας')),
                ('info', models.TextField(max_length=1000, verbose_name='Περιγραφή')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Σημειώσεις')),
                ('time', models.FloatField(verbose_name='Διάρκεια')),
                ('name', models.CharField(blank=True, help_text='Επώνυμο-Όνομα', max_length=100, null=True, verbose_name='Υπάλληλος Επικοιν.')),
                ('ticketid', models.CharField(blank=True, max_length=50, verbose_name='Αίτημα OTS')),
                ('dhmos', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='foreas.dhmos', verbose_name='Πελάτης')),
                ('employee', models.ForeignKey(default='-', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'ACS Εργασίες Φορέα',
                'verbose_name_plural': 'ACS Εργασίες Φορέα',
                'ordering': ['importdate'],
                'indexes': [models.Index(fields=['importdate', 'employee'], name='foreas_erga_importd_7c85c8_idx')],
            },
        ),
    ]
