# Generated by Django 5.2 on 2026-09-01 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeia',
            name='enddate',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Έως'),
        ),
        migrations.AlterField(
            model_name='adeia',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Από'),
        ),
    ]
