# Generated by Django 5.2 on 2026-07-28 10:48

import datetime
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_must_change_password'),
        ('parameters', '0005_jobtype_source_id_otssoftware_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('startdate', models.DateField(default=datetime.date.today, verbose_name='Από')),
                ('enddate', models.DateField(default=datetime.date.today, verbose_name='Έως')),
                ('acs_adeiatype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.acsadeia', verbose_name='Τύπος Άδειας')),
                ('acs_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'ACS Άδειες',
                'verbose_name_plural': 'ACS Άδειες',
                'indexes': [models.Index(fields=['acs_employee'], name='accounts_ad_acs_emp_9b93ba_idx')],
            },
        ),
    ]
