# Generated by Django 5.2 on 2026-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adeia'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeia',
            name='source_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
