# Generated by Django 5.2 on 2026-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adeia_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='source_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
