# Generated by Django 5.1.3 on 2024-12-03 09:51

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_address_remove_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('company_owner_name', models.CharField(max_length=255)),
                ('company_title', models.CharField(max_length=255)),
                ('company_title_alias', models.CharField(max_length=255, unique=True)),
                ('company_address', models.CharField(max_length=255)),
                ('company_city', models.CharField(max_length=100)),
                ('company_postal_code', models.CharField(max_length=20)),
                ('company_country', models.CharField(max_length=100)),
                ('company_phone_number_1', models.CharField(max_length=255)),
                ('company_phone_number_2', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Εταιρεία',
                'verbose_name_plural': 'Εταιρεία',
                'ordering': ['company_title'],
            },
        ),
    ]
