# Generated by Django 5.2 on 2026-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_leave_days',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
