# Generated by Django 5.1.3 on 2024-12-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(related_name='users', to='accounts.company'),
        ),
    ]
