# Generated by Django 5.2 on 2026-07-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_allowed_leave_days'),
        ('parameters', '0007_alter_officialholiday_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adeia',
            name='accounts_ad_acs_emp_9b93ba_idx',
        ),
        migrations.AddIndex(
            model_name='adeia',
            index=models.Index(fields=['acs_employee', 'startdate'], name='accounts_ad_acs_emp_70311d_idx'),
        ),
    ]
