# Generated by Django 5.1.3 on 2024-12-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_adeia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeia',
            name='adeiatype',
            field=models.CharField(choices=[('1', 'Κανονική'), ('2', 'Αναρρωτική'), ('3', 'Εορταστική'), ('4', 'Γονική')], default='1', max_length=1, verbose_name='Τύπος Άδειας'),
        ),
    ]
