# Generated by Django 5.2 on 2026-07-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_adeia_accounts_ad_acs_emp_9b93ba_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeia',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
