# Generated by Django 5.1.3 on 2024-12-04 08:45

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_adeia_adeiatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('company', models.CharField(choices=[('1', 'OTS'), ('2', 'ACS')], default='OTS', max_length=100, verbose_name='Φορέας')),
                ('place', models.CharField(choices=[('Remote', 'Remote'), ('Γραφεία OTS', 'Γραφεία OTS'), ('Γραφείο ACS', 'Γραφείο ACS')], default='-', max_length=100, verbose_name='Χώρος')),
                ('importdate', models.DateField(default=datetime.date.today, verbose_name='Καταχώρηση')),
                ('training_type', models.CharField(choices=[('Εκπαίδευση', 'Εκπαίδευση')], default='Εκπαίδευση', max_length=100, verbose_name='Εκαπίδευση')),
                ('app', models.CharField(blank=True, choices=[('ΤΑΠ', 'ΤΑΠ'), ('Μισθοδοσία', 'Μισθοδοσία'), ('Διαχείριση Προσωπικού', 'Διαχείριση Προσωπικού'), ('Διαχείριση Μισθωμάτων', 'Διαχείριση Μισθωμάτων'), ('Λογιστική', 'Λογιστική'), ('Μητρώο Πολιτών', 'Μητρώο Πολιτών'), ('Ύδρευση', 'Ύδρευση'), ('Αποφάσεις', 'Αποφάσεις'), ('Πρωτόκολλο', 'Πρωτόκολλο'), ('Γραφείο Κίνησης', 'Γραφείο Κίνησης'), ('Διαύγεια', 'Διαύγεια'), ('Έσοδα', 'Έσοδα'), ('Κοιμητήρια', 'Κοιμητήρια'), ('ΚΟΚ', 'ΚΟΚ'), ('Δημοτικός φόρος', 'Δημοτικός φόρος'), ('Site', 'Site'), ('Web Άδειες', 'Web Άδειες'), ('Πρακτικό', 'Πρακτικό'), ('Hardware', 'Hardware'), ('Ύδατα', 'Ύδατα'), ('OPEN1|Process', 'OPEN1|Process'), ('OPEN1|Fin', 'OPEN1|Fin'), ('OPEN1|HR', 'OPEN1|HR'), ('OPEN1|Property', 'OPEN1|Property'), ('Open1|Decisions', 'Open1|Decisions'), ('Open1|Entrance', 'Open1|Entrance'), ('OPEN1|Fleet', 'OPEN1|Fleet'), ('OPEN1|Project360', 'OPEN1|Project360'), ('4myCity', '4myCity'), ('Easy Pay', 'EasyPay'), ('Εσωτερικός Έλεγχος-Επιχ. Συν.', 'Εσωτερικός Έλεγχος-Επιχ. Συν.'), ('Ηλεκτ.Εισπρ. ΔΙΑΣ', 'Ηλεκτ.Εισπρ. ΔΙΑΣ'), ('Διαχείριση Ποιότητας - ISO', 'Διαχείριση Ποιότητας - ISO')], max_length=100, verbose_name='Εφαρμογή')),
                ('time', models.FloatField(verbose_name='Διάρκεια')),
                ('info', models.TextField(blank=True, max_length=500, null=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': 'ACS Εκπαιδεύσεις',
                'verbose_name_plural': 'ACS Εκπαιδεύσεις',
            },
        ),
        migrations.RemoveIndex(
            model_name='adeia',
            name='accounts_ad_created_5c15cb_idx',
        ),
        migrations.RemoveField(
            model_name='adeia',
            name='createddate',
        ),
        migrations.AddField(
            model_name='adeia',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adeia',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddIndex(
            model_name='adeia',
            index=models.Index(fields=['created', 'acs_employee'], name='accounts_ad_created_9a80db_idx'),
        ),
        migrations.AddField(
            model_name='training',
            name='acs_employee',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['importdate', 'acs_employee'], name='accounts_tr_importd_83e73d_idx'),
        ),
    ]
