# Generated by Django 5.1.4 on 2025-01-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='days_left',
            field=models.IntegerField(default='0', verbose_name='Υπόλοιπο προηγούμενου έτους'),
        ),
        migrations.AddField(
            model_name='user',
            name='days_sum',
            field=models.IntegerField(default='0', verbose_name='Ημέρες άδειας'),
        ),
    ]
