# Generated by Django 5.1.4 on 2025-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_created_user_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex_choice",
            field=models.CharField(
                blank=True,
                choices=[("Άνδρας", "Άνδρας"), ("Γυναίκα", "Γυναίκα")],
                max_length=10,
                verbose_name="Φύλο",
            ),
        ),
    ]
