# Generated by Django 5.1.4 on 2025-01-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_sex_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex_choice',
            field=models.CharField(blank=True, choices=[('1', 'Άνδρας'), ('2', 'Γυναίκα')], max_length=10, verbose_name='Φύλο'),
        ),
    ]
