# Generated by Django 5.2 on 2026-09-01 16:12

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcsAdeia',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Τύπος Άδειας')),
                ('adeianame_id', models.CharField(blank=True, null=True, unique=True, verbose_name='ID Τύπου Άδειας')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('source_id', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'ACS Τύπος Άδειας',
                'verbose_name_plural': 'ACS Τύποι Άδειας',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_id', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Τύπος Εργασίας',
                'verbose_name_plural': 'Τύπος Εργασίας',
            },
        ),
        migrations.CreateModel(
            name='OfficialHoliday',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgDepartment',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_id', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Διευθύνσεις Οργανισμού',
                'verbose_name_plural': 'Διευθύνσεις Οργανισμού',
            },
        ),
        migrations.CreateModel(
            name='OtsSoftware',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Εφαρμογής')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('source_id', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Λογισμικό Οργανισμού',
                'verbose_name_plural': 'Λογισμικό Οργανισμού',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlace',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Χώρος Εκπαίδευσης',
                'verbose_name_plural': 'Χώρος Εκπαίδευσης',
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Τύπος Εκπαίδευσης',
                'verbose_name_plural': 'Τύποι Εκπαίδευσης',
            },
        ),
    ]
