# Generated by Django 5.2 on 2026-07-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgSoftware',
            new_name='OtsSoftware',
        ),
        migrations.AlterModelOptions(
            name='otssoftware',
            options={'verbose_name': 'Λογισμικό Οργανισμού', 'verbose_name_plural': 'Λογισμικό Οργανισμού'},
        ),
    ]
