# Generated by Django 5.2 on 2026-07-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_rename_orgsoftware_otssoftware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdepartment',
            name='source_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
