# Generated by Django 5.2 on 2026-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_orgdepartment_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsadeia',
            name='source_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
