# Generated by Django 5.2 on 2026-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_acsadeia_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='source_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='otssoftware',
            name='source_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
