# Generated by Django 5.2 on 2026-07-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_jobtype_source_id_otssoftware_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
