# Generated by Django 5.2 on 2026-07-30 08:19

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0006_officialholiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialholiday',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='officialholiday',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialholiday',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
