# Generated by Django 5.2 on 2026-07-31 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0007_alter_officialholiday_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
