# Generated by Django 5.2 on 2026-08-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0009_alter_acsadeia_id_alter_officialholiday_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'verbose_name': 'Τύπος Εκπαίδευσης', 'verbose_name_plural': 'Τύποι Εκπαίδευσης'},
        ),
    ]
