# Generated by Django 5.2 on 2026-09-05 07:27

import django_extensions.db.fields
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('company_type', models.CharField(max_length=150)),
                ('company_address', models.CharField(max_length=150)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_afm', encrypted_model_fields.fields.EncryptedCharField()),
                ('phone_number', models.CharField(max_length=150)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Πελάτες Ταμειακών Μηχανών',
                'verbose_name_plural': 'Πελάτες Ταμειακών Μηχανών',
                'db_table': 'acs_tameiakes_customer',
                'ordering': ['last_name'],
            },
        ),
    ]
