# Generated by Django 5.2 on 2026-10-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tameiakes', '0002_alter_customer_company_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
