# Generated by Django 5.2 on 2026-10-02 07:11

import django.db.models.deletion
import django_extensions.db.fields
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tameiakes', '0003_rename_status_customer_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cash_model', models.CharField(max_length=50)),
                ('cash_number', models.CharField(max_length=50)),
                ('register_date', models.DateField(blank=True, null=True)),
                ('current_os', models.CharField(blank=True, max_length=50)),
                ('aes_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('voucher', models.BooleanField(blank=True, default=False, null=True)),
                ('iris_connect', models.BooleanField(blank=True, default=False, null=True)),
                ('pos_connect', models.BooleanField(blank=True, default=False, null=True)),
                ('cash_estiasi', models.BooleanField(blank=True, default=False, null=True)),
                ('info', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tameiakes.customer')),
            ],
            options={
                'verbose_name': 'Ταμειακές',
                'verbose_name_plural': 'Ταμειακές',
                'db_table': 'acs_tameiakes',
                'ordering': ['customer'],
            },
        ),
    ]
