# Generated by Django 5.2 on 2026-09-01 16:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255, verbose_name='Πελάτης')),
                ('org_address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Διεύθυνση')),
                ('org_city', models.CharField(blank=True, default='-', max_length=255, verbose_name='Πόλη')),
                ('org_phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('org_remote', models.CharField(blank=True, max_length=60, verbose_name='Remote')),
                ('org_email', models.EmailField(blank=True, max_length=254)),
                ('org_site', models.URLField(blank=True, max_length=250, null=True)),
                ('org_info', models.TextField(blank=True, max_length=1000, verbose_name='Πληροφορίες')),
                ('is_active', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('source_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Οργανισμός',
                'verbose_name_plural': 'Οργανισμός',
                'ordering': ('org_name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=150, verbose_name='Όνομα')),
                ('lastname', models.CharField(blank=True, max_length=150, verbose_name='Επώνυμο')),
                ('phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='Κινητό')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, verbose_name='Πληροφορίες')),
                ('is_active', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('source_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('org_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.orgdepartment', verbose_name='Τμήμα Οργανισμού')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization', verbose_name='Οργανισμός')),
            ],
            options={
                'verbose_name': 'Υπάλληλοι Οργανισμού',
                'verbose_name_plural': 'Υπάλληλοι Οργανισμού',
                'ordering': ('lastname', 'firstname'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('org_name', models.CharField(max_length=255, verbose_name='Πελάτης')),
                ('org_address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Διεύθυνση')),
                ('org_city', models.CharField(blank=True, default='-', max_length=255, verbose_name='Πόλη')),
                ('org_phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('org_remote', models.CharField(blank=True, max_length=60, verbose_name='Remote')),
                ('org_email', models.EmailField(blank=True, max_length=254)),
                ('org_site', models.URLField(blank=True, max_length=250, null=True)),
                ('org_info', models.TextField(blank=True, max_length=1000, verbose_name='Πληροφορίες')),
                ('is_active', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Οργανισμός',
                'verbose_name_plural': 'historical Οργανισμός',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('importdate', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Ημ. Κατ.')),
                ('task_info', models.TextField(max_length=1000, verbose_name='Περιγραφή εργασίας')),
                ('task_note', models.TextField(blank=True, max_length=1000, verbose_name='Σημειώσεις')),
                ('task_time', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Διάρκεια εργασίας')),
                ('ticketid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Αίτημα OTS')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('acs_employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_type_acs', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parameters.jobtype', verbose_name='Τύπος Εργασίας ACS')),
                ('org_app', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parameters.otssoftware', verbose_name='Εφαρμογή OTS')),
                ('org_employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.employee', verbose_name='Υπάλληλος')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Οργανισμός')),
            ],
            options={
                'verbose_name': 'historical Εργασίες Οργανισμού',
                'verbose_name_plural': 'historical Εργασίες Οργανισμού',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('firstname', models.CharField(blank=True, max_length=150, verbose_name='Όνομα')),
                ('lastname', models.CharField(blank=True, max_length=150, verbose_name='Επώνυμο')),
                ('phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='Κινητό')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, verbose_name='Πληροφορίες')),
                ('is_active', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org_department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parameters.orgdepartment', verbose_name='Τμήμα Οργανισμού')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Οργανισμός')),
            ],
            options={
                'verbose_name': 'historical Υπάλληλοι Οργανισμού',
                'verbose_name_plural': 'historical Υπάλληλοι Οργανισμού',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importdate', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Ημ. Κατ.')),
                ('task_info', models.TextField(max_length=1000, verbose_name='Περιγραφή εργασίας')),
                ('task_note', models.TextField(blank=True, max_length=1000, verbose_name='Σημειώσεις')),
                ('task_time', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Διάρκεια εργασίας')),
                ('ticketid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Αίτημα OTS')),
                ('source_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('acs_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('job_type_acs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.jobtype', verbose_name='Τύπος Εργασίας ACS')),
                ('org_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.otssoftware', verbose_name='Εφαρμογή OTS')),
                ('org_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.employee', verbose_name='Υπάλληλος')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Οργανισμός')),
            ],
            options={
                'verbose_name': 'Εργασίες Οργανισμού',
                'verbose_name_plural': 'Εργασίες Οργανισμού',
                'ordering': ('-importdate',),
                'indexes': [models.Index(fields=['organization', 'importdate', 'acs_employee'], name='organizatio_organiz_34436b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('training_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ημερομηνία Εκπαίδευσης')),
                ('training_time', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Διάρκεια εργασίας')),
                ('training_info', models.TextField(blank=True, max_length=500, null=True, verbose_name='Περιγραφή')),
                ('training_note', models.TextField(blank=True, max_length=500, null=True, verbose_name='Σημειώσεις')),
                ('acs_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('org_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.otssoftware', verbose_name='Εφαρμογή OTS')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Οργανισμός')),
                ('training_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.trainingtype', verbose_name='Τύπος Εκπαίδευσης')),
            ],
            options={
                'verbose_name': 'ACS Εκπαιδεύσεις',
                'verbose_name_plural': 'ACS Εκπαιδεύσεις',
                'indexes': [models.Index(fields=['training_date', 'acs_employee'], name='organizatio_trainin_c038eb_idx')],
            },
        ),
    ]
