# Generated by Django 5.2 on 2026-07-17 08:16

import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('org_name', models.CharField(max_length=255, verbose_name='Πελάτης')),
                ('org_address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Διεύθυνση')),
                ('org_city', models.CharField(blank=True, default='-', max_length=255, verbose_name='Πόλη')),
                ('org_phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('org_remote', models.CharField(blank=True, max_length=60, verbose_name='TeamViewer')),
                ('org_mail', models.EmailField(blank=True, max_length=254)),
                ('org_site', models.URLField(blank=True, max_length=250, null=True)),
                ('org_info', models.TextField(blank=True, max_length=1000, verbose_name='Πληροφορίες')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Κατάσταση')),
            ],
            options={
                'verbose_name': 'Οργανισμός',
                'verbose_name_plural': 'Οργανισμός',
                'ordering': ['org_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('org_name', models.CharField(max_length=255, verbose_name='Πελάτης')),
                ('org_address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Διεύθυνση')),
                ('org_city', models.CharField(blank=True, default='-', max_length=255, verbose_name='Πόλη')),
                ('org_phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('org_remote', models.CharField(blank=True, max_length=60, verbose_name='TeamViewer')),
                ('org_mail', models.EmailField(blank=True, max_length=254)),
                ('org_site', models.URLField(blank=True, max_length=250, null=True)),
                ('org_info', models.TextField(blank=True, max_length=1000, verbose_name='Πληροφορίες')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Οργανισμός',
                'verbose_name_plural': 'historical Οργανισμός',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
