# Generated by Django 5.2 on 2026-07-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cellphone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='historicalemployee',
            old_name='cellphone',
            new_name='mobile',
        ),
    ]
