# Generated by Django 5.2 on 2026-07-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorganization',
            old_name='org_mail',
            new_name='org_email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_mail',
            new_name='org_email',
        ),
    ]
