# Generated by Django 5.2 on 2026-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='source_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
