# Generated by Django 5.2 on 2026-08-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_historicalorganization_source_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cellphone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='historicalemployee',
            old_name='cellphone',
            new_name='mobile',
        ),
    ]
