# Generated by Django 5.2 on 2026-07-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_historicalorganization_org_remote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_visible',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='historicalemployee',
            old_name='is_visible',
            new_name='is_active',
        ),
    ]
