# Generated by Django 5.2 on 2026-08-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_rename_cellphone_employee_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='source_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
