# Generated by Django 5.2 on 2026-07-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_is_visible_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='source_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='source_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
