# Generated by Django 5.2 on 2026-08-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_employee_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='source_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
