# Generated by Django 5.2 on 2026-08-05 05:32

import datetime
import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_historicaltask_source_id_alter_task_source_id'),
        ('parameters', '0009_alter_acsadeia_id_alter_officialholiday_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('training_date', models.DateField(default=datetime.date.today, verbose_name='Ημερομηνία Εκπαίδευσης')),
                ('training_time', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Διάρκεια εργασίας')),
                ('training_info', models.TextField(blank=True, max_length=500, null=True, verbose_name='Περιγραφή')),
                ('training_note', models.TextField(blank=True, max_length=500, null=True, verbose_name='Σημειώσεις')),
                ('acs_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('org_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.otssoftware', verbose_name='Εφαρμογή OTS')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Οργανισμός')),
            ],
            options={
                'verbose_name': 'ACS Εκπαιδεύσεις',
                'verbose_name_plural': 'ACS Εκπαιδεύσεις',
                'indexes': [models.Index(fields=['training_date', 'acs_employee'], name='organizatio_trainin_c038eb_idx')],
            },
        ),
    ]
