# Generated by Django 5.2 on 2026-07-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_historicalorganization_source_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorganization',
            old_name='is_visible',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='is_visible',
            new_name='is_active',
        ),
    ]
