# Generated by Django 5.2 on 2026-08-05 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_training'),
        ('parameters', '0010_alter_trainingtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.trainingtype', verbose_name='Τύπος Εκπαίδευσης'),
        ),
    ]
