# Generated by Django 5.2 on 2026-07-25 16:36

import datetime
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_rename_is_visible_historicalorganization_is_active_and_more'),
        ('parameters', '0004_acsadeia_source_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTasks',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('importdate', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Ημ. Κατ.')),
                ('task_info', models.TextField(max_length=1000, verbose_name='Περιγραφή εργασίας')),
                ('task_note', models.TextField(blank=True, max_length=1000, verbose_name='Σημειώσεις')),
                ('task_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Διάρκεια εργασίας')),
                ('ticketid', models.CharField(blank=True, max_length=50, verbose_name='Αίτημα OTS')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('acs_employee', models.ForeignKey(blank=True, db_constraint=False, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_type_acs', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parameters.jobtype', verbose_name='Τύπος Εργασίας ACS')),
                ('org_app', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parameters.otssoftware', verbose_name='Εφαρμογή OTS')),
                ('org_employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.employee', verbose_name='Υπάλληλος')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Οργανισμός')),
            ],
            options={
                'verbose_name': 'historical Εργασίες Οργανισμού',
                'verbose_name_plural': 'historical Εργασίες Οργανισμού',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('importdate', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Ημ. Κατ.')),
                ('task_info', models.TextField(max_length=1000, verbose_name='Περιγραφή εργασίας')),
                ('task_note', models.TextField(blank=True, max_length=1000, verbose_name='Σημειώσεις')),
                ('task_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Διάρκεια εργασίας')),
                ('ticketid', models.CharField(blank=True, max_length=50, verbose_name='Αίτημα OTS')),
                ('acs_employee', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('job_type_acs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.jobtype', verbose_name='Τύπος Εργασίας ACS')),
                ('org_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.otssoftware', verbose_name='Εφαρμογή OTS')),
                ('org_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.employee', verbose_name='Υπάλληλος')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Οργανισμός')),
            ],
            options={
                'verbose_name': 'Εργασίες Οργανισμού',
                'verbose_name_plural': 'Εργασίες Οργανισμού',
                'ordering': ['importdate'],
                'indexes': [models.Index(fields=['importdate', 'acs_employee'], name='organizatio_importd_b766f3_idx')],
            },
        ),
    ]
