# Generated by Django 5.2 on 2026-07-25 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_historicaltasks_tasks'),
        ('parameters', '0004_acsadeia_source_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tasks',
            constraint=models.UniqueConstraint(fields=('ticketid',), name='unique_ticketid'),
        ),
    ]
