# Generated by Django 5.2 on 2026-07-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_tasks_unique_ticketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltasks',
            name='source_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='source_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
