# Generated by Django 5.2 on 2026-07-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_historicaltasks_source_id_tasks_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='source_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='source_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
