# Generated by Django 5.2 on 2026-07-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_employee_source_id_historicalemployee_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='org_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.employee', verbose_name='Υπάλληλος'),
        ),
    ]
