# Generated by Django 5.2 on 2026-07-27 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_alter_tasks_acs_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltasks',
            name='acs_employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος'),
        ),
        migrations.AlterField(
            model_name='historicaltasks',
            name='task_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Διάρκεια εργασίας'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='acs_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Οργανισμός'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Διάρκεια εργασίας'),
        ),
    ]
