# Generated by Django 5.2 on 2026-07-27 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_alter_historicaltasks_acs_employee_and_more'),
        ('parameters', '0005_jobtype_source_id_otssoftware_source_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-importdate'], 'verbose_name': 'Εργασίες Οργανισμού', 'verbose_name_plural': 'Εργασίες Οργανισμού'},
        ),
        migrations.RemoveIndex(
            model_name='tasks',
            name='organizatio_importd_b766f3_idx',
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['organization', 'importdate'], name='organizatio_organiz_d75411_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['acs_employee', 'importdate'], name='organizatio_acs_emp_464b4d_idx'),
        ),
    ]
