# Generated by Django 5.2 on 2026-07-27 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_tasks_options_and_more'),
        ('parameters', '0005_jobtype_source_id_otssoftware_source_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalTasks',
            new_name='HistoricalTask',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='organizatio_organiz_a501bb_idx',
            old_name='organizatio_organiz_d75411_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='organizatio_acs_emp_7c261e_idx',
            old_name='organizatio_acs_emp_464b4d_idx',
        ),
    ]
