# Generated by Django 5.2 on 2026-07-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_rename_historicaltasks_historicaltask_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name': 'Υπάλληλοι Οργανισμού', 'verbose_name_plural': 'Υπάλληλοι Οργανισμού'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Όνομα'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Επώνυμο'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization', verbose_name='Οργανισμός'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='firstname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Όνομα'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Επώνυμο'),
        ),
    ]
