# Generated by Django 5.2 on 2026-07-27 16:47

from django.db import migrations

def fill_empty_names(apps, schema_editor):
        Employee = apps.get_model("organizations", "Employee")

        Employee.objects.filter(firstname__isnull=True).update(firstname="")
        Employee.objects.filter(lastname__isnull=True).update(lastname="")
        
class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_alter_employee_options_alter_employee_email_and_more'),
    ]

    operations = [
            migrations.RunPython(fill_empty_names),
        ]