# Generated by Django 5.2 on 2026-07-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_auto_20260727_1947'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_ticketid',
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='ticketid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Αίτημα OTS'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ticketid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Αίτημα OTS'),
        ),
    ]
